### ISSUE TITLE
DifferenceHash  and PerceptualHash fails to compute hash

### ISSUE THREAD

**Issue by Gerardo-Sista** [coenm/ImageHash#21]
DifferenceHash  always fail, and also PerceptualHash fails very often (9/10) . I get images from a folder and, in a foreach statement, use this code:

```
ulong imageHash;
//this fails also if instantiated outside foreach of course
DifferenceHash DiffHashAlgorithm = new DifferenceHash();
    using (FileStream stream = File.OpenRead(MyFile.FullPath))
      {
       imageHash      = DiffHashAlgorithm.Hash(stream);
       }
```
Both algorythms give the same error:

**Exception message:**
Image cannot be loaded. Available decoders:
 - JPEG : JpegDecoder
 - BMP : BmpDecoder
 - GIF : GifDecoder
 - PNG : PngDecoder

**StackTrace:**
   in SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)    in CoenM.ImageHash.ImageHashExtensions.Hash(IImageHash hashImplementation, Stream stream)

**Files used for test**
![4512](https://user-images.githubusercontent.com/34858800/53304225-25517280-3873-11e9-86dc-79f2d104f612.jpg)
![5254 - copia 2](https://user-images.githubusercontent.com/34858800/53304226-25517280-3873-11e9-8e2a-5db560b4195b.jpg)
![5254 - copia 3](https://user-images.githubusercontent.com/34858800/53304227-25ea0900-3873-11e9-90f3-996fbffec795.jpg)
![5254 - copia 4](https://user-images.githubusercontent.com/34858800/53304228-25ea0900-3873-11e9-8f8e-04e474ac8225.jpg)
![5254 - copia 5](https://user-images.githubusercontent.com/34858800/53304229-25ea0900-3873-11e9-9421-cfc9c36f1d4e.jpg)
![5254 - copia](https://user-images.githubusercontent.com/34858800/53304230-25ea0900-3873-11e9-80eb-6da14dcba57a.jpg)
![5254](https://user-images.githubusercontent.com/34858800/53304231-26829f80-3873-11e9-83ef-3d95d9a6ea53.jpg)
![5665](https://user-images.githubusercontent.com/34858800/53304233-271b3600-3873-11e9-9c03-7c1bd55a0ae3.jpg)
![6133](https://user-images.githubusercontent.com/34858800/53304234-271b3600-3873-11e9-9350-9e411414ad9a.jpg)
![6239](https://user-images.githubusercontent.com/34858800/53304236-8ed18100-3873-11e9-98c3-572d441112df.jpg)
![8110](https://user-images.githubusercontent.com/34858800/53304237-297d9000-3873-11e9-8d36-ee378fc1dbf5.jpg)
![8874](https://user-images.githubusercontent.com/34858800/53304238-2a162680-3873-11e9-9f34-821ed1aaa38e.jpg)
![14129](https://user-images.githubusercontent.com/34858800/53304239-2aaebd00-3873-11e9-8a54-644c900bee2a.jpg)
![16858](https://user-images.githubusercontent.com/34858800/53304240-2b475380-3873-11e9-9633-e09c01c142c2.jpg)
![senza titolo](https://user-images.githubusercontent.com/34858800/53304241-2bdfea00-3873-11e9-82d2-61e754445f16.png)
![senza titolo2](https://user-images.githubusercontent.com/34858800/53304242-2bdfea00-3873-11e9-8183-f741cad223ad.png)

**Comment by coenm** [comment]
I tried the first image and I was able to calculate all three hashes. I don't know when you uploaded the images mutated the originals or not.

Can you provide some information about the operating system
Can you provide a sample git repo containing some images and some failing unittest?

Thank you.

**Comment by Gerardo-Sista** [comment]
Hello, thank you for response. Tomorrow I will prepare repo with small VS
sample tomorrow with these original images.

Il Lun 25 Feb 2019, 22:19 Coen van den Munckhof <notifications@github.com>
ha scritto:

**Comment by Gerardo-Sista** [comment]
Please clone this
https://github.com/Gerardo-Sista/ImageHashApp.git

Tested in various computers: all the same result. ERROR for Average and Diffenrence hashes.

**Comment by coenm** [comment]
I'll try to clone and take a look this evening.

**Comment by coenm** [comment]
See pull request for the fix. The stream has not been disposed but been read. By setting the positon back to 0 you can use it again for the next image hash.
