### ISSUE TITLE
How to create hash from a bitmap...

### ISSUE THREAD

**Issue by leonpotgieter** [coenm/ImageHash#24]
Hi,

I'm sampling a portion of my display and wanting to create a perceptual hash from the resulting Bitmap but can't seem to find a way to do it... all examples require loading an image from disk which I ideally do not want to use as it requires me to first save the image to disk which is slow.

Is there a simple way or method to create a hash directly from bitmap?

**Comment by LambertWM** [comment]
Not sure what you mean, the interface uses an image that is "in memory", so it is completely up to you to decide where the image originates from.

```
namespace CoenM.ImageHash
{
    public interface IImageHash
    {
        ulong Hash(Image<Rgba32> image);
    }
}
```

**Comment by developervariety** [comment]
I believe they want to create a hash out of a Bitmap so they can save it in a database perhaps. This removes the need to save all images that you already know are "good", just need to find similar ones.

I am in need of this too, but I will keep looking.

**Comment by developervariety** [comment]
It just slapped me in the face, you save the `ulong` from the "good" images in a database for later use.

@leonpotgieter I hope this solves your issue.

**Comment by coenm** [comment]
You can take a look at [this test code from ImageSharp](https://github.com/SixLabors/ImageSharp/blob/master/tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/SystemDrawingBridge.cs) where a `Bitmap` is converted to an `Image<Rgba32>` inmemory.

After obtaining such `Image<Rgb32>` you can call the `Hash(Image<Rgb32> image)` method as @LambertWM  described.

You can also try to save the Bitmap to a MemoryStream and use the following extension method.

```
        public static ulong Hash(this IImageHash hashImplementation, Stream stream)
        {
            if (hashImplementation == null)
                throw new ArgumentNullException(nameof(hashImplementation));
            if (stream == null)
                throw new ArgumentNullException(nameof(stream));

            using (var image = Image.Load<Rgba32>(stream))
                return hashImplementation.Hash(image);
        }
```
