### ISSUE TITLE
PerceptualHash and differences in computed hash value between Net5 and Net6

### ISSUE THREAD

**Issue by ThomasTosik** [coenm/ImageHash#38]
Hi,

does anyone encounter strange hash value differences when using the PerceptualHash hash function? We made some tests from Net5 to Net6 and the values produced differ. The stream and data behind stayed the same. We computed quickly a md5 hash for both stream variants (net5 and net6) and the values stayed the same.

Regards

**Comment by ThomasTosik** [comment]
It seems ImageSharp 1.0.1 has some issues with Net6 (see several github issues). After updating to 1.0.4 our Hash value stayed the same in Net6 as in Net5.

**Comment by coenm** [comment]
Hi @ThomasTosik , 
The next version of ImageHash will also reference the lastest version of ImageSharp (1.0.4)

**Comment by coenm** [comment]
A new package has been published to nuget.
