### ISSUE TITLE
Update readme example

### ISSUE THREAD

**Issue by xXBuilderBXx** [coenm/ImageHash#85]
The readme examples are out of date which would confuse some people including me the latest version of the hash functions use a sixlabors image class with specific format.

The example just shows `hashAlgorithm.Hash(stream)`

But you need to do `hashAlgorithm.Hash(SixLabors.ImageSharp.Image.Load<SixLabors.ImageSharp.PixelFormats.Rgba32>(stream))`

**Comment by coenm** [comment]
Strange, the code snippets in the readme are generated from source code. I will take a look tomorrow

**Comment by coenm** [comment]
The snippet is not out of date but is an extension method located at [ImageHashExtensions](https://github.com/coenm/ImageHash/blob/develop/src/ImageHash/ImageHashExtensions.cs#L19-L33)

The snippet is generated from [Examples.cs](https://github.com/coenm/ImageHash/blob/develop/tests/ImageHash.Test/Examples.cs#L14-L26)
